#!/bin/bash
set -ueo pipefail
script_dir=$(cd "$(dirname "$0")"; pwd)
cd "$script_dir"

install_dir=/usr/local/sbin

mkdir -pv "$install_dir"
cp -v "sysad-lib" "$install_dir"
cp -v "sysad-pubkey" "$install_dir"
cp -v "sysad-pubkey-add" "$install_dir"
cp -v "sysad-pubkey-show" "$install_dir"
cp -v "sysad-pubkey-delete" "$install_dir"

echo "sudoersのsecure_pathに下記を含めてください。"
echo "  $install_dir"
